spring.application.name=nyare

# SQLite DataSource
spring.datasource.url=jdbc:sqlite:nyare.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# HikariCP Configuration for SQLite
spring.datasource.hikari.maximum-pool-size=1

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
