spring.application.name=nyare

# Server
server.port=${SPRING_BOOT_PORT:8080}

# SQLite DataSource
spring.datasource.url=jdbc:sqlite:nyare.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# HikariCP Configuration for SQLite
spring.datasource.hikari.maximum-pool-size=1

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Jackson 3 / Spring Boot 4
spring.jackson.deserialization.fail-on-null-for-primitives=false
